

# =================================
# FUENTE
# =================================

font_family 	JetBrainsMono Nerd Font
bold_font 		auto
italic_font 	auto
bold_italic_font auto
font_size 		10.0

# Ligaduras desacivadas
disable_ligatures always


# =================================
# VENTANA
# =================================

background_opacity 0.8
window_padding_width 15
window_border_width 0
hide_window_decorations no


# =================================
# CURSOR
# =================================

cursor_shape beam
cursor_beam_thickness 1.8
cursor_blink_interval 0.5



# =================================
# COLORES · paleta azul del rice
# =================================

foreground            #e8efff
background            #050b1a
selection_foreground  #e8efff
selection_background  #1e4ed8

cursor                #38bdf8
cursor_text_color     #050b1a

url_color             #38bdf8

# negro
color0  #0a1430
color8  #1e2a4f
# rojo
color1  #f87171
color9  #fca5a5
# verde
color2  #4ade80
color10 #86efac
# amarillo
color3  #fbbf24
color11 #fcd34d
# azul
color4  #3b82f6
color12 #60a5fa
# magenta
color5  #c084fc
color13 #d8b4fe
# cian
color6  #38bdf8
color14 #7dd3fc
# blanco
color7  #a5cdff
color15 #e8efff
